import { GarmentConfig, ModelProfile, PoseSetting, BackgroundSetting, GeneratedShowcase } from '../types';

export const GARMENT_CONFIGS: GarmentConfig[] = [
  {
    id: 'saree',
    name: 'Saree',
    subtitle: 'Traditional & Designer Drapes',
    icon: '✨',
    description: 'Specialized for capturing pleat draping, pallu zari patterns, border accents, and tailored blouse cuts.',
    defaultFabric: 'Pure Kanchipuram Silk with Zari',
    slots: [
      {
        id: 'main_body',
        name: 'Saree Main Body / Field',
        shortLabel: 'Main Body',
        description: 'Upload the fabric pattern, base color, and body buttas/motifs',
        placeholder: 'e.g. Royal emerald green silk with golden floral butti work',
        required: true,
      },
      {
        id: 'pallu_design',
        name: 'Pallu (Anchal) & Border Design',
        shortLabel: 'Pallu & Border',
        description: 'Upload the grand end-piece (pallu) artwork, broad border, and zari work',
        placeholder: 'e.g. Heavy zari woven peacock motif pallu with rich golden border',
        required: true,
      },
      {
        id: 'blouse_design',
        name: 'Blouse Design & Neck Cut',
        shortLabel: 'Blouse Design',
        description: 'Upload the blouse style (sweetheart neck, elbow sleeve, back cut, embroidery)',
        placeholder: 'e.g. Contrast maroon velvet blouse with intricate zardozi maggam work',
        required: true,
      },
      {
        id: 'sub_detail',
        name: 'Close-up Texture / Trim Motif (Optional)',
        shortLabel: 'Border / Trims',
        description: 'High-detail close-up of piping, tassels, stones, or weave detail',
        placeholder: 'e.g. Intricate kaddi border with ruby stone hangings',
        required: false,
      },
    ],
  },
  {
    id: 'kurti',
    name: 'Kurti / Anarkali',
    subtitle: 'Tunics, Sets & Flared Suits',
    icon: '👗',
    description: 'Perfect for straight cut kurtas, flared Anarkalis, neckline yoke embroideries, and bottom pairings.',
    defaultFabric: 'Chanderi Silk / Georgette',
    slots: [
      {
        id: 'main_body',
        name: 'Kurti Body & Flare Print',
        shortLabel: 'Kurti Body',
        description: 'Main silhouette, flare/slit style, length, and overall fabric print',
        placeholder: 'e.g. Powder blue pastel A-line kurti with delicate floral foil prints',
        required: true,
      },
      {
        id: 'yoke_neckline',
        name: 'Front Yoke & Neckline Embroidery',
        shortLabel: 'Neck / Yoke',
        description: 'Detailed front chest yoke, collar, gota patti or threadwork design',
        placeholder: 'e.g. Intricate mirror work and chikankari handwork on sweetheart yoke',
        required: true,
      },
      {
        id: 'bottom_pant',
        name: 'Bottom / Pant / Palazzo Style',
        shortLabel: 'Bottom Wear',
        description: 'Pants, palazzo, cigarette trousers, or sharara bottom details',
        placeholder: 'e.g. Matching straight pants with scalloped organza lace border',
        required: false,
      },
      {
        id: 'dupatta_scarf',
        name: 'Dupatta / Stole Design (Optional)',
        shortLabel: 'Dupatta',
        description: 'Draped dupatta print, fabric transparency, and border tassels',
        placeholder: 'e.g. Flowy organza dupatta with scalloped borders and hand-painted flowers',
        required: false,
      },
    ],
  },
  {
    id: 'lehenga',
    name: 'Lehenga Choli',
    subtitle: 'Bridal & Festive Ensembles',
    icon: '👑',
    description: 'Tailored for voluminous lehenga skirts, choli blouses, latkans, and royal bridal drapery.',
    defaultFabric: 'Raw Silk & Multi-layer Net with Heavy Zardozi',
    slots: [
      {
        id: 'main_body',
        name: 'Lehenga Skirt & Kalis',
        shortLabel: 'Skirt / Ghera',
        description: 'Full skirt flair, panels (kalis), bottom border border ghera, and embroidery',
        placeholder: 'e.g. Crimson velvet lehenga with antique gold zardozi and 16-kali flair',
        required: true,
      },
      {
        id: 'choli_blouse',
        name: 'Choli / Blouse Top Cut',
        shortLabel: 'Choli Top',
        description: 'Blouse neckline, sleeve length, bustier fit, and front/back embroidery',
        placeholder: 'e.g. Sweetheart plunge choli with heavy pearl and sequin crystal embroidery',
        required: true,
      },
      {
        id: 'dupatta_drape',
        name: 'Dupatta Draping & Veil',
        shortLabel: 'Dupatta / Veil',
        description: 'Sheer veil or double dupatta style, border work, and shoulder drape',
        placeholder: 'e.g. Sheer net dupatta draped over shoulder with scalloped lace border',
        required: true,
      },
      {
        id: 'waist_trims',
        name: 'Latkan & Belt / Trims (Optional)',
        shortLabel: 'Latkan & Belt',
        description: 'Embroidered kamarbandh belt, handmade heavy latkans, tassels',
        placeholder: 'e.g. Matching embroidered fabric belt with crystal tassels',
        required: false,
      },
    ],
  },
  {
    id: 'salwar_suit',
    name: 'Salwar Kameez',
    subtitle: 'Classic Punjabi & Pakistani Suits',
    icon: '🥻',
    description: 'Focus on straight kurta silhouettes, salwar pleats/dhoti styling, and rich dupatta presentation.',
    defaultFabric: 'Pure Organza & Silk Crepe',
    slots: [
      {
        id: 'main_body',
        name: 'Kameez / Kurta Front & Damana',
        shortLabel: 'Kameez Top',
        description: 'Front length, side slits, daman border embroidery and sleeve cuff',
        placeholder: 'e.g. Mint green long silk kameez with heavy resham embroidery on daman',
        required: true,
      },
      {
        id: 'bottom_pant',
        name: 'Salwar / Gharara / Trouser',
        shortLabel: 'Salwar Bottom',
        description: 'Pleated salwar, flared gharara or wide palazzo styling',
        placeholder: 'e.g. Flared layered gharara with gotta patti accents',
        required: true,
      },
      {
        id: 'dupatta_scarf',
        name: 'Heavy Dupatta & Border',
        shortLabel: 'Dupatta Drape',
        description: 'Full spread dupatta print, border lace, and shoulder cascade',
        placeholder: 'e.g. Banarasi brocade woven dupatta in contrasting ruby red',
        required: true,
      },
    ],
  },
  {
    id: 'western_dress',
    name: 'Western / Gown',
    subtitle: 'Evening Gowns & Contemporary Dresses',
    icon: '💃',
    description: 'Captures modern tailoring, mermaid silhouettes, evening ballgowns, slit cuts, and satin sheen.',
    defaultFabric: 'Duchess Satin / High-sheen Silk Crepe',
    slots: [
      {
        id: 'main_body',
        name: 'Full Silhouette & Dress Cut',
        shortLabel: 'Dress Silhouette',
        description: 'Full body dress structure, waist cinch, train length, or slit styling',
        placeholder: 'e.g. Midnight navy blue satin evening gown with high leg slit and cowl drape',
        required: true,
      },
      {
        id: 'fabric_detail',
        name: 'Fabric Texture & Print Swatch',
        shortLabel: 'Fabric Texture',
        description: 'High-res close-up of the weave, sequin shine, jacquard or lace',
        placeholder: 'e.g. Micro-glitter metallic weave with liquid satin drape',
        required: true,
      },
      {
        id: 'neck_sleeve',
        name: 'Neckline & Sleeve Styling',
        shortLabel: 'Neck & Sleeve',
        description: 'Corset boning, off-shoulder, halter neck, or puff sleeve structure',
        placeholder: 'e.g. Structured boned corset sweetheart bustier with off-shoulder draped sleeves',
        required: false,
      },
    ],
  },
  {
    id: 'coord_set',
    name: 'Indo-Western & Co-ords',
    subtitle: 'Modern Blazer Sets, Capes & Dhoti Pants',
    icon: '✨',
    description: 'Designed for trending fusion outfits, long shrugs, crop top + draped skirt combinations.',
    defaultFabric: 'Modal Satin / Georgette',
    slots: [
      {
        id: 'main_body',
        name: 'Top / Crop Top / Blazer',
        shortLabel: 'Top / Blazer',
        description: 'Structure of the upper garment, collar, buttoning or embroidery',
        placeholder: 'e.g. Tailored embroidered cropped jacket with mirror work',
        required: true,
      },
      {
        id: 'bottom_pant',
        name: 'Bottoms / Draped Skirt / Dhoti',
        shortLabel: 'Bottom Wear',
        description: 'Draped tulip pants, asymmetric skirt or high-waist palazzo',
        placeholder: 'e.g. Pre-draped pleated cowl dhoti skirt with side slit',
        required: true,
      },
      {
        id: 'cape_overlay',
        name: 'Cape / Shrug / Layering (Optional)',
        shortLabel: 'Cape / Shrug',
        description: 'Floor-length sheer printed cape or organza jacket overlay',
        placeholder: 'e.g. Floor-touching flowy organza cape with botanical golden foil print',
        required: false,
      },
    ],
  },
];

export const FABRIC_PRESETS = [
  'Pure Kanchipuram Silk with Zari',
  'Organza with Hand-painted Florals',
  'Georgette with Resham Threadwork',
  'Chanderi Silk with Golden Zari',
  'Rich Velvet with Zardozi Work',
  'Banarasi Brocade Weave',
  'Mulmul Cotton with Chikankari',
  'Duchess Satin with Liquid Drape',
  'Tussar Silk with Block Prints',
  'Sheer French Net with Sequin Glass',
];

export const COLOR_PALETTES = [
  { name: 'Royal Emerald Green', hex: '#0a5c36' },
  { name: 'Deep Crimson Maroon', hex: '#780016' },
  { name: 'Regal Peacock Blue', hex: '#004953' },
  { name: 'Mustard Gold / Haldi Yellow', hex: '#e1a100' },
  { name: 'Powder Blush Pink', hex: '#e8a598' },
  { name: 'Pastel Sage Mint', hex: '#87a987' },
  { name: 'Midnight Navy Blue', hex: '#111e38' },
  { name: 'Ivory Gold Champagne', hex: '#ebd5b3' },
  { name: 'Terracotta Rust Orange', hex: '#b34728' },
  { name: 'Lavender Lilac', hex: '#9d7bb0' },
];

export const MODEL_ETHNICITIES = [
  { id: 'indian_south', name: 'South Indian Model', desc: 'Warm golden skin tone, deep brown almond eyes, classic features' },
  { id: 'indian_north', name: 'North Indian / Punjabi Model', desc: 'Radiant wheatish complexion, sharp defined jawline, regal presence' },
  { id: 'indian_kashmiri', name: 'Kashmiri / Himalayan Model', desc: 'Porcelain fair skin, subtle rosy undertones, expressive eyes' },
  { id: 'indian_contemporary', name: 'Contemporary Urban Indian', desc: 'Modern high-fashion editorial look, dewy sun-kissed skin' },
  { id: 'middle_eastern', name: 'Middle Eastern Elegance', desc: 'Olive warm tone, rich dramatic eyes, luxury editorial look' },
  { id: 'east_asian', name: 'East Asian / Pan-Asian', desc: 'Clear porcelain skin, sleek minimalist features, modern poise' },
  { id: 'caucasian', name: 'International / European', desc: 'High-fashion runway aesthetic, sharp angular features' },
  { id: 'afro_heritage', name: 'Afro-Contemporary', desc: 'Luminous rich melanin tone, striking high-fashion bone structure' },
];

export const MODEL_HAIRSTYLES = [
  'Sleek Low Bun adorned with Fresh Jasmine Gajra & Gold Hairpin',
  'Voluminous Soft Cascading Waves parted in center',
  'Traditional Long Braid (Jada) with Temple Gold Ornaments',
  'Messy Textured Modern Bun with delicate face-framing tendrils',
  'Ultra-Sleek High Fashion Ponytail with glossy finish',
  'Half-Up Regal Twist with floral hair accessories',
];

export const MODEL_MAKEUP_STYLES = [
  'Royal Wedding Glam (Defined Kohl eyeliner, warm bronze shimmer, terracotta-rose matte lips)',
  'Minimal Dewy "Clean Girl" Aesthetic (Glass skin finish, glossy peach lips, brushed natural brows)',
  'Smokey Festive High-Glam (Soft copper-gold smoked eyes, sculptured cheekbones, nude lips)',
  'Traditional Bridal Perfection (Red bindi, winged eyeliner, golden lid highlighter, rich vermilion lips)',
];

export const MODEL_JEWELRY_STYLES = [
  'Antique Temple Gold Necklace with matching Jhumkas & Maang Tikka',
  'Royal Polki Kundan Choker with Emerald Drop Beads & Matha Patti',
  'Modern Minimalist Diamond / Solitaire Necklace & Studs',
  'Vintage Oxidized Silver Boho Choker & Nose Ring (Nath)',
  'Subtle Luxury Pearl Haar (Basra Pearls) & Delicate Bangles',
  'Clean Contemporary — No heavy jewelry (Focus 100% on garment)',
];

export const POSE_PRESETS: PoseSetting[] = [
  {
    id: 'full_body_standing',
    name: 'Full Body Fashion Stance',
    description: 'Standing gracefully, slight turn to camera, one hand on hip, full garment silhouette visible.',
    cameraAngle: 'Eye-level full-length portrait shot, 85mm prime lens',
    shotType: 'full_body',
  },
  {
    id: 'saree_pallu_drape',
    name: 'Pallu / Dupatta Showcase',
    description: 'Gentle hand holding the pallu or dupatta outward to show off intricate border and woven motifs.',
    cameraAngle: 'Three-quarter editorial angle, soft motion in fabric',
    shotType: 'three_quarter',
  },
  {
    id: 'dynamic_twirl',
    name: 'Dynamic Motion / Flare Twirl',
    description: 'Model mid-twirl, garment flare expanded with physics-accurate motion, joyful confident expression.',
    cameraAngle: 'Slight low-angle action shot with high shutter speed clarity',
    shotType: 'dynamic',
  },
  {
    id: 'royal_seated',
    name: 'Royal Heritage Seated',
    description: 'Gracefully seated on a vintage velvet settee or carved jharokha step, pleats neatly arranged.',
    cameraAngle: 'Classic aristocratic portrait angle, cinematic depth',
    shotType: 'three_quarter',
  },
  {
    id: 'back_neck_detail',
    name: 'Over-the-Shoulder Back Detail',
    description: 'Looking over shoulder towards camera to prominently display the blouse back neckline cut & latkans.',
    cameraAngle: 'Medium close-up profile highlighting back embroidery and neck cut',
    shotType: 'close_up',
  },
  {
    id: 'walking_runway',
    name: 'Editorial Stride / Runway Walk',
    description: 'Walking naturally toward the camera, fabric flowing smoothly, confident high-fashion gaze.',
    cameraAngle: 'Full length forward motion portrait with realistic natural movement',
    shotType: 'full_body',
  },
];

export const BACKGROUND_SETTINGS: BackgroundSetting[] = [
  {
    id: 'luxury_studio',
    name: 'Luxury Architectural Studio',
    type: 'studio',
    description: 'Warm cream fluted limestone walls, minimalist podium, gentle archways, diffused softbox lighting.',
    lightingType: 'Soft diffused natural studio daylight with gentle warm rim light',
    ambiance: 'Sophisticated, modern high-end boutique catalog aesthetic',
    previewBg: 'linear-gradient(135deg, #f5f0eb 0%, #e2d7cb 100%)',
  },
  {
    id: 'heritage_haveli',
    name: 'Royal Rajasthan Haveli / Palace',
    type: 'heritage',
    description: 'Pink sandstone carved jharokhas, marble pillars, antique brass urli with floating marigolds, golden sunbeams.',
    lightingType: 'Golden hour warm sunlight streaming through carved lattice jaali windows',
    ambiance: 'Regal, imperial Indian royal wedding luxury',
    previewBg: 'linear-gradient(135deg, #e8c39e 0%, #a66a44 100%)',
  },
  {
    id: 'botanical_garden',
    name: 'Lush Courtyard & Blooming Bougainvillea',
    type: 'nature',
    description: 'Sunlit royal lawn, blooming magenta bougainvillea canopy, whitewashed terracotta walls, stone fountain.',
    lightingType: 'Crisp morning sunlight with warm natural highlights and leafy bokeh',
    ambiance: 'Vibrant, refreshing summer festive vibe',
    previewBg: 'linear-gradient(135deg, #d2e8d4 0%, #76a076 100%)',
  },
  {
    id: 'modern_penthouse',
    name: 'Minimalist Sunlit Loft / Penthouse',
    type: 'modern',
    description: 'Floor-to-ceiling glass windows overlooking city skyline, warm oak wood flooring, sheer curtains.',
    lightingType: 'Soft ambient side-window natural illumination',
    ambiance: 'Contemporary cosmopolitan fashion editorial',
    previewBg: 'linear-gradient(135deg, #e4e6ea 0%, #9ca3af 100%)',
  },
  {
    id: 'festive_diwali',
    name: 'Festive Evening with Warm Diyas & Fairy Lights',
    type: 'festive',
    description: 'Atmospheric evening setting with glowing brass oil lamps (diyas), subtle fairy light bokeh, marigold garland decor.',
    lightingType: 'Warm candlelight & golden ambient glow with rich shadow depth',
    ambiance: 'Grand Diwali & sangeet festive celebration',
    previewBg: 'linear-gradient(135deg, #3d1b02 0%, #804000 100%)',
  },
  {
    id: 'clean_ecommerce',
    name: 'Pure Seamless E-commerce Backdrop',
    type: 'minimal',
    description: 'Clean ivory white gradient studio sweep with subtle ground shadow. 100% garment emphasis.',
    lightingType: 'Balanced high-CRI fashion studio strobe lights (color accuracy 99%)',
    ambiance: 'Flawless commercial catalog for Amazon / Myntra / Luxury Web Store',
    previewBg: 'linear-gradient(135deg, #ffffff 0%, #e9ecef 100%)',
  },
];

export const DEMO_SHOWCASES: GeneratedShowcase[] = [
  {
    id: 'demo-saree-1',
    timestamp: Date.now() - 1000 * 60 * 30,
    garmentCategory: 'saree',
    title: 'Emerald Green Kanchipuram Bridal Saree',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80',
    masterPrompt: 'High fashion 4k commercial photograph of a stunning 24-year-old South Indian female model gracefully draped in a rich emerald green pure Kanchipuram silk saree with intricate golden zari floral butta work. Heavy contrast maroon velvet blouse with ornate zardozi neckline and elbow-length sleeves. Broad gold zari border flowing across her shoulder. Model styled with a sleek low bun wrapped with fresh white jasmine gajra, antique temple jewellery, dewy glowing skin with visible natural skin pores. Posed in a luxury sunlit haveli courtyard with marble pillars. Captured on Hasselblad H6D-100c, 85mm f/1.4 lens, soft golden hour lighting, hyperrealistic fabric weave texture, ultra photorealistic 8k --ar 3:4 --v 6.1',
    negativePrompt: 'cartoon, 3d render, CGI, plastic skin, distorted fingers, extra limbs, blurry face, low resolution, oversaturated, unrealistic fabric drape, bad anatomy, deformed eyes',
    modelConfig: {
      ethnicity: 'South Indian Model',
      ageRange: '24 years old',
      skinTone: 'Warm golden honey tone',
      hairStyle: 'Sleek Low Bun adorned with Fresh Jasmine Gajra',
      makeupStyle: 'Royal Wedding Glam',
      jewelryStyle: 'Antique Temple Gold Necklace with matching Jhumkas & Maang Tikka',
      expression: 'Serene, elegant gentle smile',
    },
    pose: 'Pallu / Dupatta Showcase - Holding the pallu outward to show the intricate border',
    background: 'Royal Rajasthan Haveli / Palace with carved sandstone and soft sunlight',
    fabricSummary: 'Pure Kanchipuram Silk with Zari & Velvet Blouse',
    referenceImages: [
      { slotName: 'Main Body', url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=400&q=80' },
      { slotName: 'Pallu & Border', url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=400&q=80' },
      { slotName: 'Blouse Design', url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80' },
    ],
  },
  {
    id: 'demo-kurti-2',
    timestamp: Date.now() - 1000 * 60 * 90,
    garmentCategory: 'kurti',
    title: 'Powder Blue Hand-Embroidered Anarkali Kurti',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1200&q=80',
    masterPrompt: 'Editorial fashion photoshoot of a beautiful 25-year-old North Indian woman wearing a pastel powder blue floor-length Anarkali kurti set in chanderi silk. Heavy chikankari hand-embroidery and mirror work along the sweetheart neckline and front yoke. Flowy lightweight organza dupatta draped over one arm with scalloped edges. Paired with slim straight pants. Model has soft beach waves, minimal dewy no-makeup makeup, natural skin texture, subtle pearl studs. Posed walking gracefully in a minimalist architectural studio with warm limestone arches and soft natural light. Shot on Sony A1, 85mm f/1.4, cinematic commercial quality, 4k ultra-detailed fabric physics --ar 3:4 --v 6.1',
    negativePrompt: 'blurry, artificial, cartoon, deformed hands, plastic skin, mannequin, low detail, bad lighting, dull colors',
    modelConfig: {
      ethnicity: 'North Indian / Punjabi Model',
      ageRange: '25 years old',
      skinTone: 'Radiant wheatish complexion',
      hairStyle: 'Voluminous Soft Cascading Waves',
      makeupStyle: 'Minimal Dewy "Clean Girl" Aesthetic',
      jewelryStyle: 'Subtle Luxury Pearl Haar & Delicate Bangles',
      expression: 'Confident, radiant high-fashion gaze',
    },
    pose: 'Editorial Stride / Runway Walk - Fabric flowing smoothly',
    background: 'Luxury Architectural Studio with warm cream fluted walls',
    fabricSummary: 'Chanderi Silk & Sheer Organza with Chikankari Work',
    referenceImages: [
      { slotName: 'Kurti Body', url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80' },
      { slotName: 'Neck / Yoke', url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80' },
    ],
  },
  {
    id: 'demo-lehenga-3',
    timestamp: Date.now() - 1000 * 60 * 180,
    garmentCategory: 'lehenga',
    title: 'Crimson Royal Velvet Bridal Lehenga',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=1200&q=80',
    masterPrompt: 'Ultra-realistic 8k bridal catalog photograph of a 26-year-old royal bride wearing a majestic deep crimson maroon velvet bridal lehenga choli. Exquisite hand-crafted gold zardozi kalis with 16-kali expansive ghera flare. Heavy sweetheart cut choli embellished with pearls and antique crystals. Double dupatta styling with a sheer peach net head veil and crimson velvet shoulder drape with heavy scalloped borders. Model with royal Polki kundan choker, matha patti, traditional kohl eyes, warm radiant bridal glow. Standing proudly in a heritage palace courtyard with glowing brass diyas and warm candlelight. Hasselblad medium format, depth of field, real human pores and fabric weave --ar 3:4 --v 6.1',
    negativePrompt: '3d cgi, drawing, anime, oversaturated, plastic mannequin, bad hands, cloned face, oversmoothed skin',
    modelConfig: {
      ethnicity: 'Royal Rajputana / North Indian',
      ageRange: '26 years old',
      skinTone: 'Warm golden glowing complexion',
      hairStyle: 'Traditional Long Braid with Temple Gold Ornaments & Head Veil',
      makeupStyle: 'Traditional Bridal Perfection with vermilion tones',
      jewelryStyle: 'Royal Polki Kundan Choker with Emerald Drop Beads & Matha Patti',
      expression: 'Regal, aristocratic poise',
    },
    pose: 'Full Body Fashion Stance - Standing gracefully, showing massive flare',
    background: 'Festive Evening with Warm Diyas & Fairy Lights in Heritage Palace',
    fabricSummary: 'Crimson Velvet with Antique Gold Zardozi & Sheer Net Veil',
    referenceImages: [
      { slotName: 'Skirt / Ghera', url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=400&q=80' },
      { slotName: 'Choli Top', url: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=400&q=80' },
      { slotName: 'Dupatta / Veil', url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=400&q=80' },
    ],
  },
];
