// ─────────────────────────────────────────────────────────────────────────────
// lib/picky-assist-push.ts
//
// Outbound helper: when a product is added/updated/deleted in our system,
// call the relevant Picky Assist Connector webhook URL to keep the
// Picky Assist Products module in sync.
//
// Each connector has a unique webhook URL generated by Picky Assist.
// Configure these in .env.local:
//
//   PICKY_ASSIST_ADD_PRODUCT_WEBHOOK_URL=https://app.pickyassist.com/hook/...
//   PICKY_ASSIST_UPDATE_PRODUCT_WEBHOOK_URL=https://app.pickyassist.com/hook/...
//   PICKY_ASSIST_DELETE_PRODUCT_WEBHOOK_URL=https://app.pickyassist.com/hook/...
//   PICKY_ASSIST_CONNECTOR_API_KEY=<key that Picky Assist requires us to send>
// ─────────────────────────────────────────────────────────────────────────────

export type PickyAssistEvent = 'add_product' | 'update_product' | 'delete_product';

export interface PickyAssistProductPayload {
  stock_code:              string;
  title?:                  string;
  description?:            string;
  price?:                  number;
  mrp?:                    number;
  quantity?:               number;
  color?:                  string;
  cloth_type?:             string;
  cover_image_url?:        string;
  tags?:                   string[];
  category?:               string;
  sub_category?:           string;
  whatsapp_catalogue_title?: string;
  instagram_caption?:      string;
  status?:                 string;
}

// Map event → env var name for the Picky Assist connector webhook URL
const WEBHOOK_URL_KEYS: Record<PickyAssistEvent, string> = {
  add_product:    'PICKY_ASSIST_ADD_PRODUCT_WEBHOOK_URL',
  update_product: 'PICKY_ASSIST_UPDATE_PRODUCT_WEBHOOK_URL',
  delete_product: 'PICKY_ASSIST_DELETE_PRODUCT_WEBHOOK_URL',
};

/**
 * Pushes a product event to the corresponding Picky Assist Connector.
 * Fire-and-forget — does NOT throw, only logs errors.
 *
 * Usage (e.g. after saving a product in your admin panel):
 *
 *   import { pushToPickyAssist } from '@/lib/picky-assist-push';
 *
 *   // When product is created:
 *   await pushToPickyAssist('add_product', { stock_code: 'RGJ-001', title: '...', price: 1299, ... });
 *
 *   // When product is updated:
 *   await pushToPickyAssist('update_product', { stock_code: 'RGJ-001', price: 999 });
 *
 *   // When product is archived/deleted:
 *   await pushToPickyAssist('delete_product', { stock_code: 'RGJ-001' });
 */
export async function pushToPickyAssist(
  event: PickyAssistEvent,
  product: PickyAssistProductPayload
): Promise<void> {
  const webhookUrlKey = WEBHOOK_URL_KEYS[event];
  const webhookUrl = process.env[webhookUrlKey];
  const apiKey = process.env.PICKY_ASSIST_CONNECTOR_API_KEY;

  if (!webhookUrl) {
    console.warn(
      `[Picky Assist Push] ${webhookUrlKey} is not set in .env.local. Skipping ${event} for ${product.stock_code}.`
    );
    return;
  }

  const body = JSON.stringify({ event, product });

  try {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };

    // Include API key if Picky Assist requires it (check their connector settings)
    if (apiKey) {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers,
      body,
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error(
        `[Picky Assist Push] ❌ ${event} for ${product.stock_code} failed. ` +
        `Status: ${response.status}. Body: ${errorText}`
      );
    } else {
      console.log(`[Picky Assist Push] ✅ ${event} pushed for ${product.stock_code}`);
    }
  } catch (err) {
    console.error(`[Picky Assist Push] ❌ Network error for ${event} (${product.stock_code}):`, err);
  }
}

/**
 * Convenience: map a Prisma product record directly to a Picky Assist payload.
 * Pass the result straight into pushToPickyAssist().
 */
export function mapProductToPickyAssistPayload(
  product: {
    stockCode:               string;
    title?:                  string | null;
    description?:            string | null;
    price?:                  number | null;
    mrp?:                    number | null;
    quantity?:               number | null;
    color?:                  string | null;
    clothType?:              string | null;
    coverImageUrl?:          string | null;
    tags?:                   string[];
    category?:               { name: string } | null;
    subCategory?:            { name: string } | null;
    whatsappCatalogueTitle?: string | null;
    instagramCaption?:       string | null;
    status?:                 string;
  }
): PickyAssistProductPayload {
  return {
    stock_code:              product.stockCode,
    title:                   product.title ?? undefined,
    description:             product.description ?? undefined,
    price:                   product.price ?? undefined,
    mrp:                     product.mrp ?? undefined,
    quantity:                product.quantity ?? undefined,
    color:                   product.color ?? undefined,
    cloth_type:              product.clothType ?? undefined,
    cover_image_url:         product.coverImageUrl ?? undefined,
    tags:                    product.tags ?? undefined,
    category:                product.category?.name ?? undefined,
    sub_category:            product.subCategory?.name ?? undefined,
    whatsapp_catalogue_title: product.whatsappCatalogueTitle ?? undefined,
    instagram_caption:       product.instagramCaption ?? undefined,
    status:                  product.status ?? undefined,
  };
}
